### ISSUE TITLE
[MacOS] ImportError: cannot import name 'TypeAlias' from 'typing' when `dave show`

### ISSUE THREAD

**Issue by cjappl** [maxmarsc/dave#5]
Repro steps are exactly the same as #4 , same program, same breakpoint.

When I:

```
(lldb) dave show data
INFO: Added data : 0
(lldb) Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/dave/server/process.py", line 103, in create_and_run
    from dave.client import DaveGUI
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/dave/client/__init__.py", line 1, in <module>
    from .gui import DaveGUI
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/dave/client/gui.py", line 7, in <module>
    import numpy as np
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/__init__.py", line 181, in <module>
    from . import lib
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/lib/__init__.py", line 23, in <module>
    from . import _index_tricks_impl
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/lib/_index_tricks_impl.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from . import defmatrix
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", line 12, in <module>
    from numpy.linalg import matrix_power
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/linalg/__init__.py", line 88, in <module>
    from . import _linalg
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/linalg/_linalg.py", line 41, in <module>
    from numpy._typing import NDArray
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/_typing/__init__.py", line 151, in <module>
    from ._scalars import (
  File "/Users/topher/.dave/venv/lib/python3.12/site-packages/numpy/_typing/_scalars.py", line 1, in <module>
    from typing import Any, TypeAlias
ImportError: cannot import name 'TypeAlias' from 'typing' (/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/typing.py)
```

Possible missing dependency? Or too-old python?

**Comment by maxmarsc** [comment]
Ok that is weird. It seems the private `dave` venv is importing some stuff from xcode's python (which should not be used, it's as mess).

Could you please try the following and give me the output ?
```bash
# Activate dave's venv
source ~/.dave/venv/bin/activate

# List all the import folders in the venv
python -c "import sys;print(sys.path)"

# Checks that numpy imports well
python -c "import numpy"

# You can then get out of the venv
deactivate
```

**Comment by cjappl** [comment]
Note I am using fish shell, so the top command is different. If this is an issue happy to test in zsh or bash.

```
> source ~/.dave/venv/bin/activate.fish
> which python
/Users/topher/.dave/venv/bin/python
> python -c "import sys;print(sys.path)"
['', '/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python312.zip', '/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12', '/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload', '/Users/topher/.dave/venv/lib/python3.12/site-packages', '/opt/homebrew/opt/python-tk@3.12/libexec']
> python -c "import numpy"
> python -c "from typing import Any, TypeAlias"
// BOTH ABOVE OK, NO ERROR
> deactivate
```

**Comment by cjappl** [comment]
If it would be easier to debug, feel free to DM me on discord and we can rapidly iterate - or we can continue chatting through this issue, whatever is most easy for you

**Comment by cjappl** [comment]
WORK AROUND:

```
brew install llvm
```

Then run this as your lldb, which seems to play nicely with dave:
```
> $(brew --prefix llvm)/bin/lldb ./build/mybin
```

**Comment by maxmarsc** [comment]
Thanks for the workaround ! I'll work on a fix within the next weeks, but it could take a bit of time so glad to have the workaround in the meantime.

**Comment by cjappl** [comment]
<img width="815" alt="Screenshot 2024-10-13 at 1 14 17 PM" src="https://github.com/user-attachments/assets/6f67e363-c0cf-4843-8a0b-9670e13a53e2">


Confirmed fixed, thanks!!
